//! Real-environment evidence (Q44).
//!
//! These tests run against the host's real `$HOME` and real Xcode installation, so they are
//! `#[ignore]`d by default and only executed on the dedicated non-blocking CI lane. Fixtures can
//! only contain what their author already imagined; a hosted image's prebuilt CoreSimulator
//! device sets were generated by Apple, not for this project.
//!
//! Two rules, both from Q44:
//!
//! - Never assert byte values. Real store sizes are non-deterministic, so only structural
//!   invariants may be asserted.
//! - Never treat this as zero-write evidence. Xcode and CoreSimulator background services mutate
//!   these directories independently, so a snapshot assertion here is flaky by construction, and
//!   a flaky gate ends up disabled with the claim left standing.

#![allow(clippy::disallowed_methods, clippy::disallowed_types)]

use std::path::Path;
use std::process::Command;

use assert_cmd::cargo::cargo_bin_cmd;
use serde_json::Value;

/// `xcode-select -p` also succeeds with only the Command Line Tools installed, where it returns
/// `/Library/Developer/CommandLineTools`. Accepting that would let both assertions below pass
/// vacuously on a host that has no Xcode at all, so the guard requires an app bundle and a
/// working `xcodebuild`.
fn require_real_xcode() -> String {
    let selected = Command::new("/usr/bin/xcode-select")
        .arg("-p")
        .output()
        .expect("xcode-select must be executable on a macOS host");
    assert!(
        selected.status.success(),
        "this lane requires a real Xcode installation; an empty result on a host without one \
         would look like success"
    );
    let developer_dir = String::from_utf8(selected.stdout)
        .expect("developer directory must be UTF-8")
        .trim()
        .to_owned();

    assert!(
        developer_dir.ends_with(".app/Contents/Developer"),
        "this lane requires a full Xcode installation, but the selected developer directory is \
         {developer_dir}; Command Line Tools alone would make every assertion below vacuous"
    );
    assert!(
        Command::new("/usr/bin/xcodebuild")
            .arg("-version")
            .output()
            .is_ok_and(|output| output.status.success()),
        "xcodebuild -version must succeed for {developer_dir}"
    );

    developer_dir
}

fn scan_real_home() -> Value {
    let output = cargo_bin_cmd!("sizetrail")
        .args(["scan", "--json"])
        .output()
        .expect("scan must run");
    assert!(
        matches!(output.status.code(), Some(0 | 3)),
        "a real-environment scan must produce a document, got exit {:?}\nstderr:\n{}",
        output.status.code(),
        String::from_utf8_lossy(&output.stderr)
    );
    serde_json::from_slice(&output.stdout).expect("stdout must be one JSON document")
}

/// A non-blocking lane whose failure is not diagnosable from its own log costs a full CI round
/// trip to explain, so every assertion below carries the typed regions and gaps with it.
fn diagnostics(document: &Value) -> String {
    format!(
        "regions={} coverage_gaps={}",
        document["payload"]["regions"], document["payload"]["coverage_gaps"]
    )
}

fn region_status(document: &Value, id: &str) -> String {
    document["payload"]["regions"]
        .as_array()
        .expect("regions must be an array")
        .iter()
        .find(|region| region["id"] == id)
        .map(|region| region["status"].to_string())
        .unwrap_or_else(|| panic!("region {id} must be reported"))
}

#[test]
#[ignore = "requires the hosted runner's real Homebrew installation"]
fn real_homebrew_storage_is_attributed_without_crossing_into_applications() {
    let prefix = [Path::new("/opt/homebrew"), Path::new("/usr/local")]
        .into_iter()
        .find(|prefix| {
            prefix.join("bin/brew").exists()
                && (prefix.join("Cellar").exists() || prefix.join("Caskroom").exists())
        })
        .expect("this lane requires the hosted runner's preinstalled Homebrew");
    let document = scan_real_home();

    assert_ne!(
        region_status(&document, "homebrew"),
        "\"not_present\"",
        "a host with {} must not report Homebrew as absent; {}",
        prefix.display(),
        diagnostics(&document)
    );
    let findings = document["payload"]["findings"]
        .as_array()
        .expect("findings must be an array")
        .iter()
        .filter(|finding| finding["adapter_id"] == "homebrew")
        .collect::<Vec<_>>();
    assert!(
        !findings.is_empty(),
        "a populated Homebrew prefix produced no findings; {}",
        diagnostics(&document)
    );
    assert!(findings.iter().all(|finding| {
        !finding["normalized_path"]
            .as_str()
            .is_some_and(|path| path.starts_with("/Applications"))
    }));
}

/// Assertion A: attribution over directories this project did not create.
#[test]
#[ignore = "requires a real Xcode installation; runs only on the Q44 lane"]
fn real_xcode_storage_produces_structurally_valid_findings() {
    let developer_dir = require_real_xcode();
    let document = scan_real_home();

    assert_eq!(
        document["schema_version"], "0.1.0-unstable",
        "developer_dir={developer_dir}"
    );
    let xcode = region_status(&document, "xcode");
    assert_ne!(
        xcode,
        "\"not_present\"",
        "a host with {developer_dir} must not report the Xcode region as absent; {}",
        diagnostics(&document)
    );

    let findings = document["payload"]["findings"]
        .as_array()
        .expect("findings must be an array");
    assert!(
        !findings.is_empty(),
        "a real Xcode host with prebuilt simulator device sets produced no findings; an empty \
         result here means the probe-to-inventory path did not run, not that storage is absent; {}",
        diagnostics(&document)
    );

    // Per category, not per total. "At least one finding" passed on a host where 133 simulator
    // device sets went unreported, because a single DerivedData finding satisfied it (Q45).
    let devices_on_disk = std::fs::read_dir(
        Path::new(&std::env::var("HOME").expect("HOME must be set"))
            .join("Library/Developer/CoreSimulator/Devices"),
    )
    .map(|entries| {
        entries
            .flatten()
            .filter(|entry| entry.path().is_dir())
            .count()
    })
    .unwrap_or(0);
    // No gap escape hatch here. Accepting "measured or declared" let a real defect through: a
    // sibling `device_set.plist` aborted the whole wildcard expansion, and the version-mismatch
    // gap was accepted as if it covered the 133 device sets it said nothing about (Q45).
    if devices_on_disk > 0 {
        assert!(
            findings
                .iter()
                .any(|finding| finding["rule_id"] == "xcode.simulator_device"),
            "{devices_on_disk} simulator device sets exist on disk but none were measured; their \
             bytes need no version-gated probe, so zero here is a traversal or gating defect; {}",
            diagnostics(&document)
        );
    }

    for finding in findings {
        assert!(
            finding["unexplained_private_gap"] == true,
            "every finding must retain unexplained_private_gap: {finding}"
        );
        assert!(
            !finding["evidence"]
                .as_str()
                .expect("evidence must be text")
                .is_empty(),
            "every finding must carry non-empty evidence: {finding}"
        );

        let measurements = finding["measurements"]
            .as_array()
            .expect("measurements must be an array");
        assert!(
            !measurements.is_empty(),
            "a finding without measurements explains nothing: {finding}"
        );

        for measurement in measurements {
            assert!(
                measurement["basis"].is_string(),
                "every measurement must name its basis: {measurement}"
            );
            assert!(
                measurement["scope"]["kind"].is_string(),
                "every measurement must name its scope: {measurement}"
            );
            if measurement["value"]["kind"] == "interval_bytes" {
                let floor = measurement["value"]["floor_bytes"]
                    .as_u64()
                    .expect("floor must be an integer");
                if let Some(ceiling) = measurement["value"]["ceiling_bytes"].as_u64() {
                    assert!(floor <= ceiling, "interval is inverted: {measurement}");
                }
            }
        }
    }
}

/// Assertion B: the version gate itself is under test. Hosted runner images rotate Xcode
/// versions constantly, so an exact-version mismatch is the expected steady state and must
/// degrade cleanly rather than fail the scan or fall back to the mutating wrapper.
#[test]
#[ignore = "requires a real Xcode installation; runs only on the Q44 lane"]
fn an_exact_version_mismatch_degrades_without_touching_the_wrapper() {
    let developer_dir = require_real_xcode();
    let document = scan_real_home();

    for gap in document["payload"]["coverage_gaps"]
        .as_array()
        .expect("coverage gaps must be an array")
    {
        assert!(
            gap["reason"].is_string(),
            "every coverage gap must carry a typed reason: {gap}"
        );
    }

    let output = cargo_bin_cmd!("sizetrail")
        .args(["doctor", "--json"])
        .output()
        .expect("doctor must run");
    let doctor: Value = serde_json::from_slice(&output.stdout).expect("doctor must emit JSON");

    let wrapper = format!("{developer_dir}/usr/bin/simctl");
    for probe in doctor["side_effect_policy"]
        .as_array()
        .expect("side-effect policy must be an array")
    {
        assert_ne!(
            probe["program"],
            wrapper.as_str(),
            "the simctl wrapper can invoke xcodebuild -runFirstLaunch and must never be a \
             registered probe: {probe}"
        );
    }
}
